search/urls.py
from django.conf.urls import include, url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'search'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^yolog/$', views.yolo_index, name='yolo_index'),
    url(r'^result/$', views.result, name='result'),
    url(r'^list/$', views.RestaurantListView.as_view(), name="rlistview"),
    url(r'^restaurants/$', views.RestaurantAllListView.as_view(), name="rallview"),
    url(r'^restaurant/(?P<venue_id>[\w-]+)/$', views.restaurantwithid,name='rwithid'),
    url(r'^restaurants/map/$', views.RestaurantAllMapListView.as_view(), name="rlistmapview"),
    url(r'^api/v1/$',views.RestaurantList.as_view()),
    url(r'^api/v1/list/new/$', views.RestDescList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

search/models.py
from django.db import models


class Restaurant(models.Model):
    name = models.CharField(max_length=400)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    address = models.CharField(max_length=500)
    checkins = models.IntegerField()
    photo_url = models.CharField(max_length=800)
    venue_id = models.CharField(max_length=500)
    phone_number = models.CharField(max_length=200,default='')
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    r_type = models.CharField(max_length=100,default="")

    def __str__(self):
        return self.name

    class Meta:
        ordering=("-checkins",)


class Location(models.Model):
    restaurant_location = models.CharField(max_length=100)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    restaurant_type = models.CharField(max_length=100,default="pizza")
    restaurant = models.ManyToManyField(Restaurant)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.restaurant_location

    class Meta:
        ordering= ("-created_at",)


class RestDesc(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="search/images/", null=True, blank=True)

    def __str__(self):
        return "{}".format(self.name)

search/views.py
import requests
import random

from django.shortcuts import render, get_object_or_404
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.db.models import Avg
from django.core.exceptions import ObjectDoesNotExist,MultipleObjectsReturned
from django.conf import settings
from django.views.generic import View
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt

from rest_framework import status, permissions
from rest_framework import mixins, generics
from rest_framework import viewsets
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser, MultiPartParser, FormParser
from rest_framework.views import APIView
from rest_framework.response import Response

from .serializers import RestaurantSerializer, RestDescSerializer
from .models import Location, Restaurant, RestDesc


GOOGLE_API_KEY = settings.GOOGLE_API_KEY
FOURSQUARE_CLIENT_ID = settings.FOURSQUARE_CLIENT_ID
FOURSQUARE_CLIENT_SECRET = settings.FOURSQUARE_CLIENT_SECRET
GOOGLE_API_KEY_JAVASCRIPT = 'GOOGLE_API_KEY_JAVASCRIPT'



class RestDescList(mixins.ListModelMixin,
                     mixins.CreateModelMixin,
                     generics.GenericAPIView):
    """
     List all restaurant, or create a restaurant
    """
    #permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    parser_classes = (JSONParser, MultiPartParser, FormParser,)
    queryset = RestDesc.objects.all()
    serializer_class = RestDescSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


def getRandomRestaurant(location,query):
    print('\n\n\n Randon rest *****\n')
    result = {}
    # Get latitude and longitude
    google_payload = {'address': location, 'key': GOOGLE_API_KEY}
    rgoogle = requests.get("https://maps.googleapis.com/maps/api/geocode/json", params=google_payload)
    googlejson = rgoogle.json()
    print(rgoogle.url)
    print('\n  *****\n')
    print(googlejson)
    status = googlejson["status"]
    if not status == "OK" :
        result["name"] = "Invalid address"
        return result
    location = googlejson['results'][0]

    # print ("Latitude and Longitude of Seoul : ",location["geometry"]["location"])
    latitude = location["geometry"]["location"]["lat"]
    longitude = location["geometry"]["location"]["lng"]
    # latitude = '41.7476'
    # longitude = '74.0868'
    latlong = str(latitude) + "," + str(longitude)

    # Get restaurant based on query
    foursquare_payload = {'client_id': FOURSQUARE_CLIENT_ID, 'client_secret': FOURSQUARE_CLIENT_SECRET, 'v' : 20160105,
    'limit':100,'ll': latlong,'query': query}

    rfoursquare = requests.get("https://api.foursquare.com/v2/venues/search",params=foursquare_payload)
    print(rfoursquare)
    fjson = rfoursquare.json()
    print(fjson)
    restaurants = fjson['response']['venues']
    total_restaurants = len(restaurants)
    restaurants_count = min(total_restaurants,100)
    if not restaurants_count > 0:
        result["name"] = "Sorry - No Restaurant found!"
        return result
    random_restaurant_index = random.randrange(0,restaurants_count)
    random_restaurant = restaurants[random_restaurant_index]
    location = random_restaurant["location"]
    formattedAddress  = []
    try:
        formattedAddress = location["formattedAddress"]
    except KeyError:
        formattedAddress[0] = "N/A"

    stats = random_restaurant["stats"]
    name = random_restaurant["name"]
    venue_id = random_restaurant["id"]
    checkIns = stats["checkinsCount"]
    contact = random_restaurant["contact"]
    phone_number = ''
    try :
        phone_number = contact["formattedPhone"]
    except KeyError:
        phone_number = 'N/A'

    result["name"] = name
    result["checkins"] = checkIns
    result["phone_number"] = phone_number
    result["address"] = (' ').join(formattedAddress)

    # Get Restaurant photo
    foursquare_payload_photo = {'client_id': FOURSQUARE_CLIENT_ID, 'client_secret': FOURSQUARE_CLIENT_SECRET, 'v' : 20160105}

    rfoursquare_photo = requests.get("https://api.foursquare.com/v2/venues/"+venue_id+"/photos",params=foursquare_payload_photo)
    # print (rfoursquare_photo.url)
    photojson = rfoursquare_photo.json()
    photos = photojson['response']['photos']
    total_photos = photos["count"]
    if total_photos > 0 :
        photos_count = min(total_photos,100)
        random_photo_index = random.randrange(0,photos_count)
        photo = photos['items'][random_photo_index]
        photo_url = photo["prefix"] + "height320" + photo["suffix"]
        # print (photo_url)
        result["image"] = photo_url
    else :
        print("no_photo")

    return result

def getRestaurantList(ilocation,query):
    rtype = query
    result = {}
    restaurantList = []
    # Get latitude and longitude
    google_payload = {'address': ilocation, 'key': GOOGLE_API_KEY}
    # google_payload = {'address': ilocation}
    rgoogle = requests.get("https://maps.googleapis.com/maps/api/geocode/json", params=google_payload)
    googlejson = rgoogle.json()
    print(rgoogle.url)
    status = googlejson["status"]
    if not status == "OK" :
        print("Invalid address - Try again")
        result["error"] = "Invalid address - Try again"
        return result
    location = googlejson['results'][0]

    # print ("Latitude and Longitude of Seoul : ",location["geometry"]["location"])
    latitude = location["geometry"]["location"]["lat"]
    longitude = location["geometry"]["location"]["lng"]
    latlong = str(latitude) + "," + str(longitude)
    loc = Location(restaurant_location=ilocation,latitude=latitude,longitude=longitude,restaurant_type=query)
    loc.save()
    # Get restaurant based on query
    foursquare_payload = {'client_id': FOURSQUARE_CLIENT_ID, 'client_secret': FOURSQUARE_CLIENT_SECRET, 'v' : 20160105,
    'limit':100,'ll': latlong,'radius':"800",'query': query}

    rfoursquare = requests.get("https://api.foursquare.com/v2/venues/search",params=foursquare_payload)
    fjson = rfoursquare.json()
    try:
        restaurants = fjson['response']['venues']
    except KeyError:
        result["error"] = "Sorry - No Restaurant found!"
        return result

    total_restaurants = len(restaurants)
    restaurants_count = min(total_restaurants,100)
    if not restaurants_count > 0:
        result["error"] = "Sorry - No Restaurant found!"
        return result
    for restaurant in restaurants:
        oneRestaurant = {}
        location = restaurant["location"]
        formattedAddress = []
        try:
            formattedAddress = location["formattedAddress"]
        except KeyError:
            formattedAddress[0] = "N/A"
        stats = restaurant["stats"]
        name = restaurant["name"]
        venue_id = restaurant["id"]
        checkIns = stats["checkinsCount"]
        contact = restaurant["contact"]
        phone_number = ''
        lat = location["lat"]
        lng = location["lng"]
        # print(lat,lng)
        try :
            phone_number = contact["formattedPhone"]
        except KeyError:
            phone_number = 'N/A'
        oneRestaurant["name"] = name
        oneRestaurant["checkins"] = checkIns
        oneRestaurant["phone_number"] = phone_number
        oneRestaurant["venue_id"] = venue_id
        oneRestaurant["address"] = (' ').join(formattedAddress)
        oneRestaurant["lat"] = lat
        oneRestaurant["lng"] = lng
        # Get Restaurant photo
        foursquare_payload_photo = {'client_id': FOURSQUARE_CLIENT_ID, 'client_secret': FOURSQUARE_CLIENT_SECRET, 'v' : 20160105}

        rfoursquare_photo = requests.get("https://api.foursquare.com/v2/venues/"+venue_id+"/photos",params=foursquare_payload_photo)
        # print (rfoursquare_photo.url)
        photojson = rfoursquare_photo.json()
        photos = photojson['response']['photos']
        total_photos = photos["count"]
        if total_photos > 0 :
            photos_count = min(total_photos,100)
            random_photo_index = random.randrange(0,photos_count)
            photo = photos['items'][random_photo_index]
            photo_url = photo["prefix"] + "455x300" + photo["suffix"]
            # print (photo_url)
            oneRestaurant["photo_url"] = photo_url
            try :
                rest = loc.restaurant.get(name=name,address=oneRestaurant["address"])

            except ObjectDoesNotExist:
                try :
                    rest = Restaurant.objects.get(name=name,address=oneRestaurant["address"],r_type=rtype)
                    rest.checkins = checkIns
                    rest.phone_number = phone_number
                    rest.save()
                    loc.restaurant.add(rest)
                    restaurantList.append(oneRestaurant)
                    print("exisiting rest found and added to location")
                except ObjectDoesNotExist:
                    rest = Restaurant(name=name,latitude=lat,longitude=lng,checkins=checkIns,phone_number=phone_number,
                        venue_id=venue_id,address=oneRestaurant["address"],photo_url=photo_url,r_type=rtype)
                    rest.save()
                    loc.restaurant.add(rest)
                    restaurantList.append(oneRestaurant)
                    print("no rest found therefore saved and added to location")
                except MultipleObjectsReturned:
                    print("multiple objects returned 1")
            except MultipleObjectsReturned:
                print("multiple objects returned 2")
        else :
            # oneRestaurant["image"] = None
            print("no_photo")

    try:
        loc = Location.objects.get(restaurant_location=ilocation,restaurant_type=rtype)
    except MultipleObjectsReturned:
        loc = loc[0]
    restaurants = loc.restaurant.all()
    result["rlist"] = restaurants
    return result

search/templates/search/all_list.html
{% extends 'search/base.html' %}
{% block fbsdkblock %} 
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '231384847207103',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

{% endblock %}

        {% block content %}
        {% if locations %}
          <div class="mdl-grid">
          {% for location in locations %}

          <div class="mdl-cell--2-col-desktop mdl-cell--3-col-tablet mdl-cell--1-offset-desktop mdl-cell--6-col-phone"> <a href="{% url 'search:rlistview' %}?location={{location.restaurant_location}}&rtype={{location.restaurant_type}}" class="mdl-button mdl-js-button mdl-js-ripple-effect">{{location.restaurant_location }} | {{location.restaurant_type}}</a>
          </div>
          <br>
          {% endfor %}

          </div>
          {% endif %}
					<div class="mdl-grid">
            {% if error %} 
            <div class="mdl-cell-middle mdl-cell--8-col mdl-cell--8-col-tablet mdl-cell--2-offset-desktop mdl-cell--12-col-phone">
            <h4>Nothing delicious here -:( </h4>
            </div>
            {% else %}
            {% if r_list %}
            <div class="mdl-cell-middle mdl-cell--8-col mdl-cell--4-offset mdl-cell--8-col-tablet mdl-cell--8-col-phone">
             <h4 class="align-center">All restaurants &amp; coffee shops</h4>
             <div id="spinner" class="mdl-spinner mdl-js-spinner is-active"></div>

             </div>

            {% for rest in r_list %}
	           <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-tablet mdl-card mdl-shadow--3dp  mdl-cell--12-col-phone">
              <div class="mdl-card__media">
               <a href="{% url 'search:rwithid' rest.venue_id %}">
                <img src="{{ rest.photo_url }}" style="max-height:300px;">
                </a>
              </div>
              <div class="mdl-card__title">
                 <h4 class="mdl-card__title-text">{{ rest.name }}</h4>
              </div>
              <div class="mdl-card__supporting-text">
                <span class="mdl-typography--font-light mdl-typography--subhead">
              {{ rest.address }}
                </span>
              </div>   
                 <div class="mdl-card__actions"> 
                <span class="mdl-badge" data-badge="♥">{{ rest.checkins }}</span>          
              </div>
              <div class="mdl-card__actions mdl-card--border post-categories post-tags">
              <a class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised">
                {{ rest.r_type }}
              </a>
               </div>
              <div class="mdl-card__menu">
                <a href="" onclick="fbshare('{{rest.venue_id}}','{{rest.photo_url}}','{{rest.name}}')">
                  <i class="material-icons" style="color: white;">share</i>
                </a>
              </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="mdl-cell-middle mdl-cell--8-col mdl-cell--8-col-tablet mdl-cell--2-offset-desktop mdl-cell--2-offset-tablet mdl-card  mdl-cell--12-col-phone">
            <h4 class="align-center">No restaurants in the bucket list -:(</h4>
            </div>
            {% endif %}

            {% endif %}
					</div>

  {% endblock %}
  {% block jsblock1 %}
    <script>
      function load() {
        var spinner = document.getElementById("spinner");
        console.log("load event detected!");
        spinner.classList.remove("is-active");
      }
      window.onload = load;
    </script>
  {% endblock %}
  {% block fbshare %} 
<script>
    function fbshare(venue_id,photo_url,title){
        FB.ui({
          method: 'share',
          href: 'https://searchrestaurant.pythonanywhere.com/restaurant/'+venue_id,
          picture: photo_url,
          caption: title,
        }, function(response){});
    }
</script>
{% endblock %}

search/templates/search/all_list_map.html
{% extends 'search/base.html' %}
{% load staticfiles %}
        {% block content %}

          {% if locations %}
          <div class="mdl-grid">
          {% for location in locations %}

          <div class="mdl-cell--2-col-desktop mdl-cell--3-col-tablet mdl-cell--1-offset-desktop mdl-cell--6-col-phone"> <a href="{% url 'search:rlistview' %}?location={{location.restaurant_location}}&rtype={{location.restaurant_type}}" class="mdl-button mdl-js-button mdl-button--primary">{{location.restaurant_location }}| {{location.restaurant_type}}</a>
          </div>
          <br>
          {% endfor %}

          </div>
          {% endif %}

					<div class="mdl-grid">
            {% if error %} 
            <div class="mdl-cell-middle mdl-cell--8-col mdl-cell--8-col-tablet mdl-cell--2-offset mdl-cell--12-col-phone">
            <h4>Nothing delicious here -:( </h4>
            </div>
            {% else %}
            {% if r_list %}
            <div class="mdl-cell-middle mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-phone">
             <h4 class="align-center" style="margin: 20px;">All restaurants &amp; coffee shops</h4>
             <div id="spinner" class="mdl-spinner mdl-js-spinner is-active align-center"></div>
            <div id="map"></div>
             </div>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAg2StWdwwf2v8OcHJNJtAcxgkygU5rROo&callback=initMap" async defer></script>
             <script>
              var marker;
              var markers = [];
              var labels = []; 
              var icons = [];
              var addresses = [];
              var titles = [];
              var map;
              var infowindows = [];
              var global_markers = [];

              function initMap() {
                var map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 3,
                  center: {lat: {{ avgLat.latitude__avg }}, lng: {{ avgLng.longitude__avg }}}
                })
                 infowindow = new google.maps.InfoWindow({});
                 addMarkers(markers,labels,map,icons,addresses,titles);

                }

                function addMarkers(locations, labels,map,icons,addresses,titles) {
                 for (var i =0; i < locations.length; i++) {
                    var marker = new google.maps.Marker({
                      position: locations[i],
                      title: labels[i],
                      animation: google.maps.Animation.DROP,
                      map: map,
                      icon: icons[i],
                      title: titles[i]
                    });
                var contentString = '<div class="mdl-grid">'+
                    '<div class="mdl-cell mdl-cell--12-col"><h4>'+
                    titles[i] +'</h4></div>'+
                    '<div class="mdl-cell mdl-cell--12-col">'+
                    '<p>' + addresses[i] + 
                    '</p>'+
                    '</div>'+
                    '</div>';
                     marker['infowindow'] = contentString;

                      global_markers[i] = marker;

                      google.maps.event.addListener(global_markers[i], 'click', function() {
                          infowindow.setContent(this['infowindow']);
                          infowindow.open(map, this);
                      });

                  }

                }
  

            </script>
            {% for rest in r_list %}
            <script>
              var restLtnLng = { lat: {{rest.latitude}}, lng: {{rest.longitude}} };
              var label = "{{rest.r_type}}"
              var icon ;
              var REST_TYPE_IMAGES = ["burger", "pizza", "coffee", "beer","wine","restaurant"];
              var ifPresent = REST_TYPE_IMAGES.indexOf(label);
              if(ifPresent != -1) {
              icon = "https://searchrestaurant.pythonanywhere.com/static/search/images/" + label +".png";

              } else {
              icon = "http://searchrestaurant.pythonanywhere.com//static/search/images/map_marker.png";

              }
              // var icon = "{% static 'search/images/{{rest.r_type}' %}";
              icons.push(icon);
              markers.push(restLtnLng);
              labels.push(label);
              addresses.push("{{rest.address}}");
              titles.push("{{rest.name}}");
            </script>

            {% if forloop.last %}
            <script>

            </script>
            {% endif %}
	           
            {% endfor %}
            {% else %}
            <div class="mdl-cell-middle mdl-cell--8-col mdl-cell--8-col-tablet mdl-cell--2-offset mdl-card mdl-shadow--3dp  mdl-cell--12-col-phone">
            <h4 class="align-center">Nothing found for the given search</h4>
            </div>
            {% endif %}

            {% endif %}
					</div>

  {% endblock %}
  {% block jsblock1 %}

    <script>
      function load() {
        var spinner = document.getElementById("spinner");
        console.log("load event detected!");
        spinner.classList.remove("is-active");
      }
      window.onload = load;
    </script>
  {% endblock %}

search/templates/search/base.html
{% load staticfiles %}
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Find delicious food nearby!">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Search Restaurant</title>

    <!-- Page styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.1/material.min.css">
    <link rel="stylesheet" href="{% static 'search/css/styles.css' %}">
    {% block opengraph %}
    <meta property="og:image" content="{% static 'search/images/food_kitchen.jpg' %}" />
    <meta property="og:url"  content="https://searchrestaurant.pythonanywhere.com" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Search Restaurant" />
    <meta property="og:description" content="Search delicious restaurant nearby you!" />
      {% endblock %}
  </head>
  <body>
  {% block fbsdkblock %} {% endblock %}
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

      <div class="scan-header mdl-layout__header mdl-layout__header--waterfall">
        <div class="mdl-layout__header-row">
          <a href="/" style="text-decoration: none;color: #767676;" class="scan-title mdl-layout-title">
          Search Restaurant
          </a>
          <!-- Add spacer, to align navigation to the right in desktop -->
          <div class="scan-header-spacer mdl-layout-spacer"></div>
          <div class="scan-search-box mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right mdl-textfield--full-width">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search-field">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" id="search-field">
            </div>
          </div>
          <!-- Navigation -->
          <div class="scan-navigation-container">
            <nav class="scan-navigation mdl-navigation">
              <a id="demo-show-toast1" class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-typography--text-uppercase" href="{% url 'search:rallview' %}">Restaurants</a>
              <a href="{% url 'search:rlistmapview' %}" class="mdl-navigation__link mdl-typography--text-uppercase">
                <i class="material-icons">location_on</i>
                </a>
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="https://github.com/hassanabidpk/searchrestaurant/blob/master/API_DOC.md">API</a>
            </nav>
          </div>
           <a href="/" style="text-decoration: none;color: #767676;" class="scan-mobile-title mdl-layout-title" style="color: #767676;">
           Search Restaurant
          </a>
          <button class="scan-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="more-button">
            <i class="material-icons">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect" for="more-button">
            <li class="mdl-menu__item">coming soon</li>
          </ul>
        </div>
      </div>

      <div class="scan-drawer mdl-layout__drawer">
        <a class="mdl-layout-title"  <a href="/" style="text-decoration: none;color: #767676;">
          Search Restaurant
        </a>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'search:rallview' %}">Restaurants</a>
          <a href="{% url 'search:rlistmapview' %}" class="mdl-navigation__link mdl-typography--text-uppercase">
                <i class="material-icons">location_on</i>
                </a>
          <a class="mdl-navigation__link mdl-typography--text-uppercase" href="https://github.com/hassanabidpk/searchrestaurant/blob/master/API_DOC.md">API</a>
          <div class="scan-drawer-separator"></div>
        </nav>
      </div>

      <div class="scan-content mdl-layout__content">
        <a name="top"></a>
        {% block content %}
        {% endblock %}
        <footer class="scan-footer mdl-mega-footer">

          <div class="mdl-mega-footer--middle-section">
            <p class="mdl-typography--font-light">© 2016 Search Restaurant</p>
          </div>

          <div class="mdl-mega-footer--bottom-section">
            <a class="scan-link scan-link-menu mdl-typography--font-light" id="version-dropdown">
              Versions
              <i class="material-icons">arrow_drop_up</i>
            </a>
            <ul class="mdl-menu mdl-js-menu mdl-menu--top-left mdl-js-ripple-effect" for="version-dropdown">
              <li class="mdl-menu__item">v1</li>
            </ul>
            <a class="scan-link scan-link-menu mdl-typography--font-light" id="developers-dropdown">
              For Developers
              <i class="material-icons">arrow_drop_up</i>
            </a>
            <ul class="mdl-menu mdl-js-menu mdl-menu--top-left mdl-js-ripple-effect" for="developers-dropdown">
            </ul>
            <a class="scan-link mdl-typography--font-light" href="">Privacy Policy</a>
          </div>

        </footer>
      </div>
    </div>
    {% block jsblock1 %}{% endblock %}
    <script src="https://code.getmdl.io/1.1.1/material.min.js"></script>
    {% block fbshare %} {% endblock %}
  </body>
</html>